- name: docker_playbook
  hosts: servers
  tasks:
    - name: build docker image 
      community.docker.docker_image:
        path: ./Dockerfile
        name: tomcat3
        tag: 1
        source: build
        push: yes
        
        
