- name: docker_playbook
  hosts: servers
  tasks:
    - name: build docker image 
      docker_image:
        name: manikanta448/tomcat:latest
    - name: docker_container
      docker_container:
        name: tomcat2
        image: manikanta448/tomcat:latest
        ports: 
          - "8086:8080"
        tty: true
        detach: true
          
          
