- name: docker_playbook
  hosts: servers
  become: true
  tasks:
    - name: docker issue
      ansible.builtin.shell:
        cmd: apt install python2-pip -y ; pip3 install docker-py ; apt update -y
    - name: build docker image 
      docker_image:
        path: Dockerfile
        name: tomcat3
        tag: 1
        source: build
        push: yes
