- name: docker_playbook
  hosts: servers
  tasks:
    - name: build docker image 
      docker_image:
        become: true
        path: ./Dockerfile
        name: tomcat3
        tag: 1
        source: build
        push: yes
