- name: docker_playbook
  hosts: servers
  become_user: root
  tasks:
    - name: build docker image 
      docker_image:
        path: ~/Dockerfile
        name: tomcat3
        tag: 1
        source: build
        push: yes
