
- name: docker_playbook
  hosts: localhost
  tasks:
    - name: docker_login
      ansible.builtin.shell: 
        cmd: echo $docker_login_PSW | docker login -u $docker_login_USR --password-stdin
    - name: docker_image_build
      docker_image:
        name: manikanta448/tomcat
        tag: 3
        push: yes
        source: build
        
        
- name: docker images pull
  hosts: servers
  tasks:
    - name: build docker image 
      docker_image:
        name: manikanta448/tomcat:1
    - name: docker_container
      docker_container:
        name: tomcat3
        image: manikanta448/tomcat:1
        ports: 
          - "8087:8080"
        tty: true
        detach: true
          
          
